import { MCQQuestion, SubjectType } from './src/types';
import { stageAiGeneratedQuestions, approveStagedQuestion } from './src/lib/firestoreService';
import { db } from './src/lib/firebase';
import { collection, getDocs, query, where } from 'firebase/firestore';

// 50 AI-generated questions for database seeding
const seedQuestions: Array<Omit<MCQQuestion, 'id'> & { id?: string }> = [
  // BIOLOGY - 10 questions
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Cell Structure and Function',
    topic: 'Nucleus and Nucleolus function',
    question: 'Which cell structure is primarily responsible for the synthesis of ribosomal RNA (rRNA) and the assembly of ribosomal subunits in eukaryotic cells?',
    options: ['Golgi apparatus', 'Nucleolus', 'Endoplasmic reticulum', 'Mitochondria'],
    correctIndex: 1,
    explanation: 'The nucleolus is a dense, non-membrane-bound structure inside the nucleus responsible for transcribing rRNA and assembling ribosomal RNA with proteins to form ribosomal subunits.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Recall',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Cell Structure and Function',
    topic: 'Lysosomes and enzyme activity',
    question: 'Hydrolytic enzymes present inside lysosomes function optimally under which internal pH environment?',
    options: ['Strongly alkaline (pH 10-12)', 'Neutral (pH 7.0-7.4)', 'Acidic (pH 4.5-5.0)', 'Weakly alkaline (pH 8.0-8.5)'],
    correctIndex: 2,
    explanation: 'Lysosomes contain acid hydrolases that require an acidic pH (around 4.5-5.0) for optimal activity, maintained by proton pumps embedded in the lysosomal membrane.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Recall',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Cell Structure and Function',
    topic: 'Fluid Mosaic Model of Cell Membrane',
    question: 'According to the Fluid Mosaic Model of the cell membrane, the property of membrane fluidity is mainly attributed to the:',
    options: ['Continuous rigid layer of extrinsic proteins', 'Lateral movement of phospholipids within the bilayer', 'Fixed arrangement of cholesterol molecules', 'Carbohydrate chains attached to the outer surface'],
    correctIndex: 1,
    explanation: 'The lipid bilayer exhibits fluid behavior because individual phospholipid molecules can move laterally within their layer, allowing membrane proteins to drift as well.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Cell Structure and Function',
    topic: 'Cytoskeleton structure and components',
    question: 'Which cytoskeleton component is composed of tubulin protein dimers and forms the structural basis of cilia, flagella, and centrioles?',
    options: ['Microfilaments', 'Intermediate filaments', 'Microtubules', 'Myosin filaments'],
    correctIndex: 2,
    explanation: 'Microtubules are hollow cylinders made of alpha and beta tubulin dimers. They constitute the structural framework of centrioles, spindle fibers, cilia, and flagella.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Recall',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Cell Structure and Function',
    topic: 'Functions of Endoplasmic Reticulum',
    question: 'Which organelle function is directly associated with the Smooth Endoplasmic Reticulum (SER)?',
    options: ['Synthesis of secretory proteins', 'Detoxification of harmful drugs and lipid synthesis', 'Modification and packaging of proteins into vesicles', 'Intracellular digestion of macromolecules'],
    correctIndex: 1,
    explanation: 'Smooth Endoplasmic Reticulum (SER) lacks ribosomes and is predominantly involved in lipid and steroid synthesis, carbohydrate metabolism, and detoxification of drugs and poisons, particularly in liver cells.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Enzymes and Metabolism',
    topic: 'Enzyme Kinetics and Reversible Inhibition Types',
    question: 'A research team isolated a specific enzyme involved in glycolysis and analyzed its reaction kinetics with and without Inhibitor X. They observed that in the presence of Inhibitor X, the maximum velocity (Vmax) of the reaction remained unchanged when substrate concentration was increased significantly, but the substrate concentration needed to reach half of Vmax (Km) was significantly elevated. What can be concluded about Inhibitor X?',
    options: ['Inhibitor X is a non-competitive inhibitor that binds to an allosteric site and lowers enzyme affinity.', 'Inhibitor X is a competitive inhibitor that structurally resembles the substrate and reversibly competes for the active site.', 'Inhibitor X is an uncompetitive inhibitor that binds exclusively to the enzyme-substrate complex.', 'Inhibitor X is an irreversible inhibitor that forms covalent bonds with active site residues, reducing the total active enzyme concentration.'],
    correctIndex: 1,
    explanation: 'In competitive inhibition, the inhibitor competes directly with the substrate for binding to the active site because it resembles the substrate\'s chemical structure. This increases the Michaelis constant (Km), indicating a decrease in apparent substrate affinity. However, because the inhibition is reversible and competitive, adding excess substrate can fully outcompete the inhibitor and restore the maximum reaction velocity (Vmax). Non-competitive inhibition, by contrast, lowers Vmax without changing Km.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Enzymes and Metabolism',
    topic: 'Enzyme Conjugates (Apoenzyme, Holoenzyme, Prosthetic Group)',
    question: 'Enzyme Z requires a non-protein organic group tightly bound to its protein component via covalent bonds for catalytic activity. When the protein part is isolated completely from this non-protein moiety, it is found to be catalytically inactive. Which pair correctly identifies the isolated protein component and the non-protein component, respectively?',
    options: ['Apoenzyme; Prosthetic group', 'Holoenzyme; Coenzyme', 'Apoenzyme; Inorganic activator', 'Holoenzyme; Prosthetic group'],
    correctIndex: 0,
    explanation: 'An inactive, purely protein part of an enzyme lacking its essential cofactor/coenzyme is called an apoenzyme. When an organic cofactor is tightly or covalently bound to the apoenzyme, it is specifically termed a prosthetic group (e.g., heme group in cytochromes or biotin in carboxylases). The complete, active enzyme-cofactor complex is called a holoenzyme.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Enzymes and Metabolism',
    topic: 'Allosteric Regulation and Feedback Inhibition in Metabolic Pathways',
    question: 'In a metabolic pathway involving four sequential steps (A → B → C → D → E), Enzyme 1 converts Substrate A into Intermediate B. Accumulation of the final Product E results in the shutdown of the entire pathway due to Product E binding to a non-catalytic regulatory site on Enzyme 1. Which mechanism best describes this phenomenon?',
    options: ['Competitive feedback inhibition where Product E competes directly with Substrate A at the active site of Enzyme 1.', 'Non-competitive allosteric feedback inhibition where Product E induces a conformational change in Enzyme 1.', 'Irreversible covalent modification where Product E hydrolyzes the active site residues of Enzyme 1.', 'Positive feedback regulation where Product E accelerates the breakdown of Intermediate B.'],
    correctIndex: 1,
    explanation: 'This scenario describes feedback inhibition (end-product inhibition) operating via an allosteric mechanism. The end-product (Product E) acts as an allosteric inhibitor by binding to a regulatory (allosteric) site on the first enzyme of the pathway (Enzyme 1). This non-competitive binding induces a conformational change in the enzyme\'s active site, preventing Substrate A from binding efficiently, thereby shutting down the metabolic pathway when product levels are high.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Enzymes and Metabolism',
    topic: 'Effects of Temperature on Enzyme Tertiary Structure and Denaturation',
    question: 'An enzymatic reaction conducted at standard physiological conditions (37°C, pH 7.4) displays high catalytic rate by lowering the activation energy barrier from 85 kJ/mol to 25 kJ/mol. If the mixture temperature is rapidly raised to 75°C, the reaction rate initially rises briefly due to thermal motion but then plummets to near zero. Which molecular change accounts for this sudden loss of catalytic activity?',
    options: ['Thermal energy increases the activation energy back to 85 kJ/mol without affecting enzyme tertiary structure.', 'Thermal energy breaks weak non-covalent interactions (hydrogen bonds, ionic bonds) essential for tertiary structure, causing active site denaturation.', 'High temperature converts the enzyme substrate into an unreactive isomer incapable of forming an enzyme-substrate complex.', 'The peptide bonds forming the primary amino acid sequence of the enzyme are rapidly hydrolyzed by ambient heat.'],
    correctIndex: 1,
    explanation: 'Excessive thermal energy disrupts non-covalent interactions (such as hydrogen bonds, hydrophobic interactions, and ionic interactions) that stabilize the enzyme\'s specific 3D tertiary structure. This leads to denaturation—a loss of native conformation and destruction of the catalytic active site architecture. Peptide bonds (primary structure) are generally stable at 75°C and do not spontaneously hydrolyze without strong acids, bases, or peptidases.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Biology' as SubjectType,
    chapter: 'Enzymes and Metabolism',
    topic: 'Mechanism of Enzyme Action (Induced Fit Model and Transition State)',
    question: 'According to Koshland\'s Induced Fit Model of enzyme catalysis, how does the binding of a substrate to the enzyme\'s active site facilitate the lowering of activation energy during a reaction?',
    options: ['The active site remains completely rigid, forcing the substrate into a planar configuration that lowers reaction free energy.', 'Substrate binding induces a dynamic structural change in the enzyme that puts physical strain on substrate bonds, stabilizing the transition state.', 'The enzyme forms irreversible covalent cross-links with the substrate, permanently changing the enzyme\'s active site sequence.', 'The enzyme increases the kinetic energy of substrate molecules, raising thermal collisions to equal the activation energy barrier.'],
    correctIndex: 1,
    explanation: 'Koshland\'s Induced Fit Model proposes that the active site is flexible, not rigid. When the substrate enters the active site, it induces a conformational change in the enzyme. This precise fit puts strain on specific chemical bonds within the substrate molecule and aligns catalytic functional groups, thereby stabilizing the high-energy transition state and lowering the activation energy barrier required for the reaction to proceed.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },

  // CHEMISTRY - 10 questions
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Atomic Structure and Periodic Trends',
    topic: 'Quantum Numbers and Electronic Configuration',
    question: 'Which set of quantum numbers represents the valence electron of a ground-state Sodium atom (Z = 11)?',
    options: ['n = 3, l = 0, m = 0, s = +1/2', 'n = 3, l = 1, m = 0, s = +1/2', 'n = 2, l = 1, m = -1, s = -1/2', 'n = 3, l = 2, m = 0, s = +1/2'],
    correctIndex: 0,
    explanation: 'The electronic configuration of Sodium (Z = 11) in the ground state is 1s² 2s² 2p⁶ 3s¹. The outermost (valence) electron is in the 3s orbital. For a 3s orbital, the principal quantum number n = 3, azimuthal quantum number l = 0, magnetic quantum number m = 0, and spin quantum number s = +1/2 (or -1/2).',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Recall',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Atomic Structure and Periodic Trends',
    topic: 'Ionization Energy Trends and Stability',
    question: 'The first ionization energy of Nitrogen is higher than that of Oxygen. What is the primary reason for this exception to the general trend?',
    options: ['Nitrogen has a smaller atomic radius than Oxygen', 'Nitrogen has a stable half-filled 2p subshell configuration', 'Oxygen has a lower nuclear charge than Nitrogen', 'Nitrogen experiences a greater shielding effect than Oxygen'],
    correctIndex: 1,
    explanation: 'Nitrogen has the electronic configuration 1s² 2s² 2p³, possessing a half-filled 2p subshell which imparts extra stability. Oxygen has the configuration 1s² 2s² 2p⁴. Removing an electron from Nitrogen requires extra energy to break this stable half-filled configuration, making its first ionization energy higher than that of Oxygen.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Atomic Structure and Periodic Trends',
    topic: 'Ionic Radius of Isoelectronic Species',
    question: 'Among the following isoelectronic species, which one has the smallest ionic radius?',
    options: ['O²⁻', 'F⁻', 'Na⁺', 'Mg²⁺'],
    correctIndex: 3,
    explanation: 'All four ions (O²⁻, F⁻, Na⁺, Mg²⁺) are isoelectronic, having 10 electrons each. For isoelectronic species, as the atomic number (nuclear charge Z) increases, the attractive force of the nucleus on the electron cloud increases, pulling the electrons closer and decreasing the radius. Mg²⁺ has the highest nuclear charge (Z = 12) among the choices, giving it the smallest ionic radius.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Atomic Structure and Periodic Trends',
    topic: 'Hydrogen Spectrum Series',
    question: 'In the atomic spectrum of hydrogen, which series of spectral lines falls within the visible region of electromagnetic radiation?',
    options: ['Lyman series', 'Balmer series', 'Paschen series', 'Brackett series'],
    correctIndex: 1,
    explanation: 'The Balmer series corresponds to electron transitions from higher energy levels (n₂ = 3, 4, 5...) down to the second energy level (n₁ = 2). The energy involved in these transitions corresponds to wavelengths in the visible region of the electromagnetic spectrum.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Recall',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Atomic Structure and Periodic Trends',
    topic: 'Electron Affinity Trends and Anomalies',
    question: 'Why is the electron affinity of Chlorine greater (more negative) than that of Fluorine?',
    options: ['Chlorine has higher electronegativity than Fluorine', 'Fluorine has strong inter-electronic repulsion in its compact 2p subshell', 'Chlorine has a smaller atomic size than Fluorine', 'Fluorine has a higher nuclear charge than Chlorine'],
    correctIndex: 1,
    explanation: 'Fluorine has an extremely small atomic size, resulting in a high electron density in its compact 2p subshell. When an additional electron approaches, it experiences strong inter-electronic repulsion, which decreases the energy released during electron addition. Chlorine has a larger 3p subshell with lower electron density, so it accommodates the incoming electron with less repulsion, releasing more energy.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Chemical Bonding and Molecular Structure',
    topic: 'VSEPR Theory and Hybridization',
    question: 'Which pair of chemical species possesses the same hybridization of the central atom (sp³d) and an identical linear molecular geometry?',
    options: ['I₃⁻ and XeF₂', 'ClO₃⁻ and XeF₂', 'SF₄ and I₃⁻', 'XeF₄ and I₃⁻'],
    correctIndex: 0,
    explanation: 'Both I₃⁻ and XeF₂ have 5 electron pairs around the central atom (2 bonding pairs and 3 lone pairs), giving sp³d hybridization. To minimize lone pair-lone pair repulsions, the 3 lone pairs occupy the equatorial positions of a trigonal bipyramidal arrangement, resulting in a linear molecular geometry for both species.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Chemical Bonding and Molecular Structure',
    topic: 'Molecular Orbital Theory and Bond Properties',
    question: 'According to Molecular Orbital Theory (MOT), which option correctly arranges the species O₂, O₂⁺, O₂⁻, and O₂²⁻ in order of increasing bond length, and correctly identifies the paramagnetic species with the highest bond order?',
    options: ['Order: O₂⁺ < O₂ < O₂⁻ < O₂²⁻; Paramagnetic species with highest bond order: O₂⁺', 'Order: O₂²⁻ < O₂⁻ < O₂ < O₂⁺; Paramagnetic species with highest bond order: O₂²⁻', 'Order: O₂⁺ < O₂ < O₂⁻ < O₂²⁻; Paramagnetic species with highest bond order: O₂', 'Order: O₂ < O₂⁺ < O₂⁻ < O₂²⁻; Paramagnetic species with highest bond order: O₂⁺'],
    correctIndex: 0,
    explanation: 'Bond orders calculated via MOT are: O₂⁺ = 2.5, O₂ = 2.0, O₂⁻ = 1.5, and O₂²⁻ = 1.0. Since bond length is inversely proportional to bond order, the increasing order of bond length is O₂⁺ < O₂ < O₂⁻ < O₂²⁻. Among these, O₂⁺ has 15 electrons with 1 unpaired electron in a π*2p antibonding orbital, making it paramagnetic with the highest bond order (2.5).',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Chemical Bonding and Molecular Structure',
    topic: 'Fajan\'s Rules and Polarization',
    question: 'Applying Fajan\'s rules to lithium halides (LiF, LiCl, LiBr, LiI), which compound exhibits the maximum covalent character and lowest melting point, and what is the underlying reason?',
    options: ['LiI, because the large I⁻ anion is highly polarizable by the small Li⁺ cation.', 'LiF, because the high electronegativity of fluorine causes maximum charge polarization.', 'LiCl, because of equal contribution of ionic and covalent forces in its crystal lattice.', 'LiI, because the small Li⁺ cation has low polarizing power on large anions.'],
    correctIndex: 0,
    explanation: 'Fajan\'s rules state that covalent character increases with a small cation and a large, easily polarizable anion. Li⁺ is small and common to all options. The size of the halide anion increases as F⁻ < Cl⁻ < Br⁻ < I⁻. The electron cloud of the large I⁻ ion is most easily distorted (polarized) by Li⁺, generating maximum covalent character and significantly lowering its melting point compared to other lithium halides.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Chemical Bonding and Molecular Structure',
    topic: 'Resonance and Formal Charge',
    question: 'In the resonance hybrid of the phosphate ion (PO₄³⁻), assuming phosphorus expands its octet to form one P=O double bond and three P-O⁻ single bonds, what are the formal charge on each oxygen atom and the average P-O bond order, respectively?',
    options: ['-0.75 and 1.25', '-1.00 and 1.00', '-0.50 and 1.50', '-0.75 and 1.50'],
    correctIndex: 0,
    explanation: 'In PO₄³⁻, phosphorus forms 1 double bond and 3 single bonds with 4 oxygen atoms, giving a total of 5 bonds distributed equally across 4 equivalent resonance structures. Average bond order = total P-O bonds / number of oxygen atoms = 5 / 4 = 1.25. The net charge of -3 is delocalized equally over 4 oxygen atoms, yielding a formal charge of -3 / 4 = -0.75 per oxygen atom.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Chemistry' as SubjectType,
    chapter: 'Chemical Bonding and Molecular Structure',
    topic: 'Intermolecular Forces and Hydrogen Bonding',
    question: 'Despite fluorine being more electronegative than oxygen, water (H₂O) has a significantly higher boiling point (100°C) than hydrogen fluoride (HF, 19.5°C). What is the primary structural reason for this difference?',
    options: ['Water forms a 3D hydrogen-bonded network averaging 4 hydrogen bonds per molecule, whereas HF forms linear chains averaging 2 hydrogen bonds per molecule.', 'The O-H bond is more polar than the F-H bond because oxygen has a larger atomic radius.', 'HF molecules undergo extensive intramolecular hydrogen bonding which reduces intermolecular attraction.', 'Liquid water contains coordinate covalent bonds that increase its thermal stability compared to HF.'],
    correctIndex: 0,
    explanation: 'An individual F-H...F bond is stronger than an O-H...O bond due to fluorine\'s higher electronegativity. However, each H₂O molecule has 2 hydrogen atoms and 2 lone pairs, allowing it to form an average of 4 hydrogen bonds per molecule in a 3D network. HF has 3 lone pairs but only 1 hydrogen atom, limiting its capacity to an average of 2 hydrogen bonds per molecule in 1D chains. Consequently, total intermolecular cohesion energy per mole is much higher in water.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },

  // PHYSICS - 10 questions
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Mechanics and Motion',
    topic: 'Projectile Motion',
    question: 'At what angle of projection is the horizontal range of a projectile equal to its maximum height?',
    options: ['45°', '60°', '76°', '30°'],
    correctIndex: 2,
    explanation: 'The horizontal range is given by R = (v² sin 2θ) / g and maximum height by H = (v² sin² θ) / (2g). Setting R = H gives (2 sin θ cos θ) / g = (sin² θ) / (2g), which simplifies to 4 cos θ = sin θ, or tan θ = 4. Therefore, θ = tan⁻¹(4) ≈ 76°.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Mechanics and Motion',
    topic: 'Impulse and Momentum',
    question: 'A constant force of 20 N acts on a body of mass 5 kg for 3 seconds. What is the change in momentum of the body?',
    options: ['12 N s', '60 N s', '300 N s', '15 N s'],
    correctIndex: 1,
    explanation: 'According to Newton\'s second law in terms of momentum, Impulse = Force × time = Change in momentum (Δp). Thus, Δp = F × Δt = 20 N × 3 s = 60 N s (or 60 kg m/s).',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Mechanics and Motion',
    topic: 'Work Done by a Constant Force',
    question: 'A force of 50 N pulls a block along a horizontal surface through a displacement of 10 m. If the force is applied at an angle of 60° to the horizontal, what is the work done on the block?',
    options: ['500 J', '250 J', '433 J', '100 J'],
    correctIndex: 1,
    explanation: 'Work done is calculated using the formula W = F d cosθ. Here, F = 50 N, d = 10 m, and θ = 60°. So, W = 50 × 10 × cos(60°) = 500 × 0.5 = 250 J.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Mechanics and Motion',
    topic: 'Centripetal Acceleration',
    question: 'If the linear speed of an object moving along a circular path of constant radius is doubled, how does its centripetal acceleration change?',
    options: ['It is halved', 'It is doubled', 'It increases by a factor of 4', 'It remains unchanged'],
    correctIndex: 2,
    explanation: 'Centripetal acceleration is given by a_c = v² / r. Since a_c is directly proportional to the square of the speed (v²), doubling the speed (2v)² results in four times the original centripetal acceleration (4 a_c).',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Mechanics and Motion',
    topic: 'Elastic Collisions in One Dimension',
    question: 'A body of mass \'m\' moving with velocity \'v\' undergoes a perfectly elastic head-on collision with an identical stationary body of mass \'m\'. What is the velocity of the first body after the collision?',
    options: ['v', 'v / 2', 'Zero', '-v'],
    correctIndex: 2,
    explanation: 'In a head-on perfectly elastic collision between two bodies of equal mass where one is initially at rest, the bodies exchange their velocities completely. Therefore, the moving body comes to rest (velocity = 0) and the stationary body moves with velocity \'v\'.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Electricity and Magnetism',
    topic: 'Velocity selector and cyclotron motion of a charged particle in a magnetic field',
    question: 'A proton enters a region of mutually perpendicular uniform electric field E = 2.0 × 10⁵⁴ V/m and magnetic field B = 0.5 T undeflected. If the electric field is suddenly turned off while keeping the magnetic field unchanged, what will be the radius of the circular path executed by the proton? (Mass of proton = 1.67 × 10⁻²⁷ kg, charge of proton = 1.6 × 10⁻¹⁹ C)',
    options: ['0.835 mm', '1.670 mm', '0.418 mm', '3.340 mm'],
    correctIndex: 0,
    explanation: 'When the proton moves undeflected through crossed fields, the electric and magnetic forces balance: qE = qvB, giving a velocity v = E / B = (2.0 × 10⁵⁴ V/m) / 0.5 T = 4.0 × 10⁵⁴ m/s. When the electric field is turned off, the magnetic force provides the centripetal force: qvB = mv² / r, so r = mv / (qB). Substituting the values: r = (1.67 × 10⁻²⁷ kg × 4.0 × 10⁵⁴ m/s) / (1.6 × 10⁻¹⁹ C × 0.5 T) = 6.68 × 10⁻²⁷ / 8.0 × 10⁻²⁰ = 8.35 × 10⁻⁴ m = 0.835 mm.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Electricity and Magnetism',
    topic: 'Energy conservation and maximum current in LC oscillations',
    question: 'A capacitor of capacitance C = 20 μF is fully charged to a potential difference of 100 V using a DC source. It is then disconnected from the source and connected across an ideal inductor of inductance L = 50 mH. Assuming negligible resistance in the circuit, what is the maximum current that flows through the inductor during the resulting LC oscillations?',
    options: ['1.0 A', '2.0 A', '4.0 A', '0.5 A'],
    correctIndex: 1,
    explanation: 'According to the principle of conservation of energy in an LC circuit, the maximum electrostatic energy stored in the capacitor equals the maximum magnetic energy stored in the inductor: (1/2) C V² = (1/2) L I_max². Solving for I_max gives I_max = V × √(C / L). Substituting the values: I_max = 100 × √((20 × 10⁻⁶ F) / (50 × 10⁻³ H)) = 100 × √(4 × 10⁻⁴) = 100 × 0.02 = 2.0 A.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Electricity and Magnetism',
    topic: 'Electric potential along the equatorial axis of a dipole and work done on a charge',
    question: 'Two equal and opposite point charges +q and -q are fixed at points (-a, 0) and (+a, 0) respectively on the x-axis, forming an electric dipole. A third positive test charge +q₀ is moved from point (0, a) to point (0, 3a) along the y-axis. What is the net work done by the electrostatic field on the test charge during this motion?',
    options: ['Zero', '(k q q₀ / a) × (1/√2 - 1/√10)', '(2 k q q₀) / (a × 10)', '(k q q₀) / (2a)'],
    correctIndex: 0,
    explanation: 'The y-axis represents the perpendicular bisector (equatorial line) of the electric dipole. At any point on the y-axis, the distance to +q and -q is identical, making the electric potential V = k(q/r) + k(-q/r) = 0 everywhere along the y-axis. Since the potential at both the initial position (0, a) and final position (0, 3a) is zero, the potential difference ΔV = 0. The work done by the electrostatic field is W = -q₀ ΔV = 0.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Electricity and Magnetism',
    topic: 'Magnetic field of a solenoid and magnetic force on a moving charge',
    question: 'A tightly wound long solenoid of length L = 0.5 m has N = 1000 turns and carries a steady current I = 2.0 A. An electron is projected directly along the central longitudinal axis of the solenoid with a velocity of 1.0 × 10⁶ m/s. What is the magnitude of the magnetic force acting on the electron as it moves inside the solenoid?',
    options: ['0 N', '8.0 × 10⁻¹⁴ N', '5.0 × 10⁻¹⁴ N', '3.2 × 10⁻¹⁵ N'],
    correctIndex: 0,
    explanation: 'Inside a long solenoid, the magnetic field B is directed parallel to the central axis. Since the electron is projected along the central axis, its velocity vector v is parallel (or antiparallel) to the magnetic field vector B, making the angle θ = 0° (or 180°). The magnetic force on a moving charge is given by F = q v B sin(θ). Since sin(0°) = 0, the magnetic force acting on the electron is strictly zero.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Physics' as SubjectType,
    chapter: 'Electricity and Magnetism',
    topic: 'Temperature dependence of resistance and Wheatstone bridge balance conditions',
    question: 'Four metallic resistors R_A, R_B, R_C, and R_D are arranged to form a Wheatstone bridge circuit. At 0°C, all four resistors have an equal resistance of 10 Ω. R_A and R_C are made of a material with a temperature coefficient of resistance α = 4.0 × 10⁻³ K⁻¹, while R_B and R_D are made of a material with α = 1.0 × 10⁻³ K⁻¹. If the temperature of all four resistors is uniformly increased to 100°C, what is the equivalent resistance of the bridge network across the supply terminals?',
    options: ['10.0 Ω', '12.5 Ω', '14.0 Ω', '25.0 Ω'],
    correctIndex: 1,
    explanation: 'At 100°C, the new resistances are given by R(T) = R₀(1 + αΔT). R_A(100) = R_C(100) = 10(1 + 4.0 × 10⁻³ × 100) = 14 Ω. R_B(100) = R_D( 100) = 10(1 + 1.0 × 10⁻³ × 100) = 11 Ω. In the standard bridge arrangement (arm 1: R_A in series with R_B; arm 2: R_C in series with R_D), the balance condition ratio is R_A / R_B = R_C / R_D. Since R_A / R_B = 14 / 11 and R_C / R_D = 14 / 11, the bridge remains balanced, and no current flows through the central branch. The equivalent resistance is the parallel combination of the two arms: R_eq = (R_A + R_B) || (R_C + R_D) = (14 + 11) || (14 + 11) = 25 || 25 = 12.5 Ω.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },

  // ENGLISH - 10 questions
  {
    subject: 'English' as SubjectType,
    chapter: 'Vocabulary and Contextual Meaning',
    topic: 'Contextual Synonyms',
    question: 'Choose the word closest in meaning to the underlined word: \'The doctor urged the patient to avoid sedentary habits to maintain good cardiovascular health.\'',
    options: ['Active and energetic', 'Inactive and desk-bound', 'Hazardous and risky', 'Stress-free and peaceful'],
    correctIndex: 1,
    explanation: 'In this context, \'sedentary\' refers to a lifestyle characterized by much sitting and little physical exercise. Therefore, \'inactive and desk-bound\' is the correct contextual synonym.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Vocabulary and Contextual Meaning',
    topic: 'Contextual Antonyms',
    question: 'Select the option that is OPPOSITE in meaning to the underlined word: \'Her candid remarks during the interview surprised everyone, as most candidates tend to be evasive.\'',
    options: ['Frank', 'Deceitful', 'Blunt', 'Sincere'],
    correctIndex: 1,
    explanation: '\'Candid\' means truthful, straightforward, and frank. The exact opposite in meaning among the options is \'deceitful\', which means misleading or dishonest.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Vocabulary and Contextual Meaning',
    topic: 'Vocabulary - Contextual Meaning',
    question: 'Choose the word closest in meaning to the underlined word: \'The scientist\'s meticulous research methods ensured that no errors were made during the experiment.\'',
    options: ['Careless', 'Thorough', 'Rapid', 'Hesitant'],
    correctIndex: 1,
    explanation: '\'Meticulous\' means showing great attention to detail, very careful, and precise. \'Thorough\' best matches this definition in the given sentence context.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Vocabulary and Contextual Meaning',
    topic: 'Contextual Vocabulary Interpretation',
    question: 'In the following sentence, what does the word \'transient\' most nearly mean? \'The sudden power outage caused a transient panic among the hospital staff, but generators restored order within minutes.\'',
    options: ['Permanent', 'Temporary', 'Overwhelming', 'Severe'],
    correctIndex: 1,
    explanation: '\'Transient\' means lasting only for a short time or impermanent. The context shows the panic quickly subsided once generators turned on, making \'temporary\' the correct meaning.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Vocabulary and Contextual Meaning',
    topic: 'Contextual Word Replacement',
    question: 'Which of the following words can best replace the underlined word without changing the meaning of the sentence? \'The professor provided a lucid explanation of the complex genetic pathway.\'',
    options: ['Clear', 'Confusing', 'Vague', 'Lengthy'],
    correctIndex: 0,
    explanation: '\'Lucid\' means expressed clearly or easy to understand. Replacing it with \'clear\' maintains the original meaning of the sentence.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Grammar and Sentence Structure',
    topic: 'Conditional Inversion and Correlative Conjunction Structures',
    question: 'Which of the following sentences demonstrates correct grammatical structure, combining third conditional inversion and inverted correlative conjunctions correctly?',
    options: ['Had the research team conducted a more thorough trial, not only would the side effects have been identified, but the efficacy of the novel drug would also have been validated.', 'Had the research team conducted a more thorough trial, not only the side effects would have been identified, but also the efficacy of the novel drug would be validated.', 'Had the research team conducted a more thorough trial, not only would the side effects be identified, but the efficacy of the novel drug would also have been validated.', 'Having the research team conducted a more thorough trial, not only would the side effects have been identified, but the efficacy of the novel drug would also have been validated.'],
    correctIndex: 0,
    explanation: 'Option A correctly handles two complex grammatical rules: (1) Third Conditional Inversion (\'Had the research team conducted...\') which eliminates \'if\' and replaces it with auxiliary inversion, paired with \'would have + past participle\' in the result clause; and (2) Negative/Correlative Inversion (\'not only would the side effects have been...\'), which requires subject-auxiliary inversion after \'not only\'. Option B misses inversion after \'not only\' and has a tense mismatch (\'would be\'). Option C mixes present and past conditional verb forms inconsistently. Option D incorrectly uses a present participle (\'Having\') instead of inverted auxiliary \'Had\'.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Grammar and Sentence Structure',
    topic: 'Dangling and Misplaced Modifiers',
    question: 'Identify the sentence that is grammatically correct and free from dangling or misplaced modifiers.',
    options: ['Having analyzed the blood samples under the high-powered microscope, the anomalous cell structures were immediately documented by the pathologist.', 'Having analyzed the blood samples under the high-powered microscope, the pathologist immediately documented the anomalous cell structures.', 'Analyzing the blood samples under the high-powered microscope, the anomalous cell structures were immediately documented by the pathologist.', 'Having analyzed the blood samples under the high-powered microscope, the pathologist\'s notes immediately documented the anomalous cell structures.'],
    correctIndex: 1,
    explanation: 'In Option B, the introductory participial phrase \'Having analyzed the blood samples under the high-powered microscope\' logically modifies the subject directly following it (\'the pathologist\'). In Options A and C, the modifier incorrectly attaches to \'the anomalous cell structures\' (implying the cells analyzed the samples). In Option D, the modifier attaches to \'the pathologist\'s notes\' (a possessive noun entity that cannot physically analyze samples), creating a dangling modifier.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Grammar and Sentence Structure',
    topic: 'Parallel Structure with Correlative Conjunctions',
    question: 'Select the sentence that maintains strict grammatical parallelism across coordinate structures.',
    options: ['The new clinical guidelines require physicians not only to monitor pediatric patients closely but also adapting the dosage according to body mass index.', 'The new clinical guidelines require physicians to not only monitor pediatric patients closely but also adapt the dosage according to body mass index.', 'The new clinical guidelines require physicians not only to monitor pediatric patients closely but also to adapting the dosage according to body mass index.', 'The new clinical guidelines require physicians to monitor pediatric patients closely not only, but also to adapt the dosage according to body mass index.'],
    correctIndex: 1,
    explanation: 'Option B exhibits correct parallel structure with correlative conjunctions: \'to\' introduces two parallel base verbs (\'not only monitor ... but also adapt\'). Option A violates parallelism by pairing an infinitive structure (\'to monitor\') with a gerund (\'adapting\'). Option C incorrectly follows \'to\' with a gerund (\'to adapting\'). Option D places \'not only\' incorrectly after the verb phrase, disrupting parallel framing.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Grammar and Sentence Structure',
    topic: 'Mandative Subjunctive Mood',
    question: 'Which of the following sentences correctly utilizes the mandative subjunctive mood in formal English syntax?',
    options: ['The ethics committee recommended that the surgeon performs the procedure only after obtaining written informed consent.', 'The ethics committee recommended that the surgeon perform the procedure only after obtaining written informed consent.', 'The ethics committee recommended that the surgeon performed the procedure only after obtaining written informed consent.', 'The ethics committee recommended that the surgeon has to perform the procedure only after obtaining written informed consent.'],
    correctIndex: 1,
    explanation: 'The mandative subjunctive is used in \'that\'- clauses following verbs of demand, recommendation, or insistence (e.g., recommend, insist, demand). It requires the base/bare form of the verb regardless of the subject or main clause tense. In Option B, \'perform\' is the uninflected base form required after \'recommended that the surgeon...\'. Options A, C, and D use indicative forms (\'performs\', \'performed\', \'has to perform\') which violate formal mandative subjunctive rules.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'English' as SubjectType,
    chapter: 'Grammar and Sentence Structure',
    topic: 'Negative Adverbial Inversion and Subject-Verb Agreement',
    question: 'Scarcely had the novel vaccine been released when one of the lead researchers, along with his assistants, were awarded the national honor.',
    options: ['Scarcely had the novel vaccine been released when one of the lead researchers, along with his assistants, was awarded the national honor.', 'Scarcely had the novel vaccine been released than one of the lead researchers, along with his assistants, was awarded the national honor.', 'Scarcely had the novel vaccine been released when one of the lead researchers, along with his assistants, was awarded the national honor.', 'Scarcely the novel vaccine had been released when one of the lead researchers, along with his assistants, was awarded the national honor.'],
    correctIndex: 2,
    explanation: 'Option C satisfies two critical advanced rules: (1) Negative Adverbial Inversion: Starting a sentence with \'Scarcely\' requires auxiliary-subject inversion (\'had the novel vaccine been released\') and pairs with \'when\' (not \'than\', which belongs to \'No sooner\'). (2) Subject-Verb Agreement: Intervening prepositional phrases like \'along with his assistants\' do not alter the grammatical number of the subject. The core subject is singular \'one\' (\'one ... was awarded\'). Option A incorrectly uses plural \'were\'. Option B incorrectly pairs \'Scarcely\' with \'than\'. Option D fails to invert the auxiliary verb after \'Scarcely\'.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },

  // LOGICAL REASONING - 10 questions
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Sequence and Pattern Recognition',
    topic: 'Exponential Difference / Multiplication Sequence',
    question: 'What number comes next in the given sequence?\n3, 5, 9, 17, 33, ?',
    options: ['65', '64', '50', '67'],
    correctIndex: 0,
    explanation: 'The sequence follows a pattern where each number is multiplied by 2 and then subtracted by 1: (3 × 2) - 1 = 5, (5 × 2) - 1 = 9, (9 × 2) - 1 = 17, (17 × 2) - 1 = 33. Therefore, the next term is (33 × 2) - 1 = 65. Alternatively, the difference between consecutive terms doubles each time (+2, +4, +8, +16, +32), giving 33 + 32 = 65.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Sequence and Pattern Recognition',
    topic: 'Alphabetical Shift Pattern',
    question: 'Identify the missing letter in the given sequence:\nC, F, I, L, O, ?',
    options: ['P', 'Q', 'R', 'S'],
    correctIndex: 2,
    explanation: 'In the English alphabet, each letter advances by 3 positions: C (+3) → F (+3) → I (+3) → L (+3) → O (+3) → R. Positionally: 3, 6, 9, 12, 15, 18. The 18th letter of the alphabet is R.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Sequence and Pattern Recognition',
    topic: 'Alphanumeric Dual Pattern Recognition',
    question: 'Which term completes the following alphanumeric sequence?\nA2, C4, E8, G16, ?',
    options: ['H32', 'I32', 'I24', 'J32'],
    correctIndex: 1,
    explanation: 'This is a dual pattern sequence: 1) The letters move forward by 2 positions: A (+2) → C (+2) → E (+2) → G (+2) → I. 2) The numbers double in each term: 2 (A2) → 4 (A4) → 8 (A8) → 16 (A16) → 32. Combining both results in I32.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Understanding',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Sequence and Pattern Recognition',
    topic: 'Increasing Difference Pattern',
    question: 'Find the next number in the following series:\n2, 6, 12, 20, 30, 42, ?',
    options: ['52', '54', '56', '60'],
    correctIndex: 2,
    explanation: 'The differences between consecutive terms form an arithmetic progression of even numbers: 6 - 2 = 4, 12 - 6 = 6, 20 - 12 = 8, 30 - 20 = 10, 42 - 30 = 12. The next difference should be 14. Adding 14 to 42 gives 42 + 14 = 56. (Alternatively, terms are n × (n + 1): 1×2 = 2, 2×3 = 6, 3×4 = 12, 4×5 = 20, 5×6 = 30, 6×7 = 42, 7×8 = 56).',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Sequence and Pattern Recognition',
    topic: 'Interleaved Series Pattern',
    question: 'Find the missing number in the following sequence:\n80, 10, 70, 15, 60, 20, ?',
    options: ['25', '50', '55', '45'],
    correctIndex: 1,
    explanation: 'This sequence consists of two interleaved series: First series (odd positions): 80, 70, 60, ... (decreases by 10 each time). Second series (even positions): 10, 15, 20, ... (increases by 5 each time). The required term is the 7th position, which belongs to the first series: 60 - 10 = 50.',
    difficulty: 'Easy',
    type: 'Standard',
    cognitiveLevel: 'Application',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Deductive Reasoning and Syllogisms',
    topic: 'Syllogistic Possibility and Universal/Particular Negation',
    question: 'Read the statements carefully and determine which of the conclusions logically follow(s).\n\nStatements:\n1. No doctor is uneducated.\n2. Some uneducated people are patients.\n3. All patients are citizens.\n4. Some citizens are not doctors.\n\nConclusions:\nI. Some citizens are definitely not uneducated.\nII. Some patients being doctors is a possibility.',
    options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions I and II follow', 'Neither conclusion I nor II follows'],
    correctIndex: 1,
    explanation: 'Conclusion I does not necessarily follow because while some citizens are uneducated (from premises 2 and 3), the premises do not guarantee that any citizen is educated (not uneducated). Premise 4 states \'Some citizens are not doctors\', but these non-doctor citizens could still all be uneducated. Conclusion II follows as a valid possibility: although some uneducated people are patients (and cannot be doctors), there may be other patients who are educated and could potentially be doctors, since no premise forbids overlap between educated patients and doctors.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Deductive Reasoning and Syllogisms',
    topic: 'Conditional Logic, Contrapositive Chain, and Fallacy of Denying the Antecedent',
    question: 'Consider the following clinical rules and findings:\n1. If a patient presents with elevated troponin, then myocardial infarction is diagnosed.\n2. If myocardial infarction is diagnosed, immediate catheterization is performed.\n3. If immediate catheterization is performed, the patient is admitted to the ICU.\n\nFindings:\n- Patient A was NOT admitted to the ICU.\n- Patient B did NOT present with elevated troponin.\n\nWhich of the following inferences MUST be logically true?',
    options: ['Patient A was not diagnosed with myocardial infarction, and Patient B was not admitted to the ICU.', 'Patient A was not diagnosed with myocardial infarction, and Patient A did not present with elevated troponin.', 'Patient B was not diagnosed with myocardial infarction, but was admitted to the ICU.', 'Patient A and Patient B both underwent immediate catheterization.'],
    correctIndex: 1,
    explanation: 'This question tests hypothetical syllogism and the law of contrapositive (If P → Q → R → S, then ~S → ~R → ~Q → ~P). For Patient A, who was not admitted to the ICU (~S), the full contrapositive chain applies: ~S → ~R (no catheterization), ~R → ~Q (no MI diagnosis), and ~Q → ~P (no elevated troponin). Therefore, Patient A was not diagnosed with MI AND did not present with elevated troponin. For Patient B, denying the antecedent (~P) is a logical fallacy and gives no definitive conclusion about Patient B\'s ICU status.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Deductive Reasoning and Syllogisms',
    topic: 'Disjunctive Syllogism and Chain Deduction',
    question: 'Analyze the following medical protocol premises:\n1. Either the cardiac enzyme test is positive, or the patient has stable angina.\n2. If the patient has stable angina, then exercise stress testing is recommended.\n3. Exercise stress testing is NOT recommended for Patient X.\n4. All patients with a positive cardiac enzyme test require continuous ECG monitoring.\n\nWhich of the following is a logically necessary conclusion regarding Patient X?',
    options: ['Patient X requires continuous ECG monitoring.', 'Patient X has stable angina.', 'Patient X does not have a positive cardiac enzyme test.', 'Patient X requires exercise stress testing.'],
    correctIndex: 0,
    explanation: 'Step 1: Patient X is NOT recommended exercise stress testing (~E). From Premise 2 (Stable Angina → Exercise Stress Testing), applying Modus Tollens (~E → ~Stable Angina), Patient X does NOT have stable angina. Step 2: Premise 1 gives a disjunction (Positive Cardiac Enzyme Test OR Stable Angina). Since Patient X does not have stable angina, by Disjunctive Syllogism, Patient X MUST have a positive cardiac enzyme test. Step 3: From Premise 4 (Positive Cardiac Enzyme Test → Continuous ECG Monitoring), by Modus Ponens, Patient X requires continuous ECG monitoring.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Deductive Reasoning and Syllogisms',
    topic: 'Categorical Syllogism with Venn Diagram Inclusion/Exclusion',
    question: 'Statements:\n1. No antibiotics are effective against viral infections.\n2. Some drugs effective against viral infections are immunomodulators.\n3. All immunomodulators are classified as specialized therapeutics.\n\nConclusions:\nI. Some specialized therapeutics are definitely not antibiotics.\nII. No antibiotic is a specialized therapeutic.\n\nSelect the correct option:',
    options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions I and II follow', 'Neither conclusion I nor II follows'],
    correctIndex: 0,
    explanation: 'From Premise 2, there exist drugs that belong to both \'Viral Effective\' and \'Immunomodulators\'. From Premise 3, all \'Immunomodulators\' belong to \'Specialized Therapeutics\'. Thus, there are \'Specialized Therapeutics\' that are effective against viral infections. From Premise 1, no drug effective against viral infections can be an antibiotic. Therefore, those specific \'Specialized Therapeutics\' cannot be antibiotics, proving Conclusion I (\'Some specialized therapeutics are definitely not antibiotics\'). Conclusion II claims NO antibiotic is a specialized therapeutic, which is invalid because antibiotics could overlap with other non-viral specialized therapeutics.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  },
  {
    subject: 'Logical Reasoning' as SubjectType,
    chapter: 'Deductive Reasoning and Syllogisms',
    topic: 'Multi-Premise Categorical Deduction and Fallacy of Undistributed Middle',
    question: 'Statements:\n1. All neuropathies cause sensory deficits.\n2. Some sensory deficits lead to impaired gait.\n3. No condition that leads to impaired gait is easily treatable.\n4. Some neuropathies are metabolic disorders.\n\nEvaluate the following inferences:\nInference 1: Some metabolic disorders cause sensory deficits.\nInference 2: No neuropathy is easily treatable.',
    options: ['Only Inference 1 logically follows', 'Only Inference 2 logically follows', 'Both Inference 1 and Inference 2 logically follow', 'Neither Inference 1 nor Inference 2 logically follows'],
    correctIndex: 0,
    explanation: 'Inference 1: From Statement 4, there is an overlap between Neuropathies and Metabolic Disorders. From Statement 1, ALL Neuropathies cause sensory deficits. Therefore, the metabolic disorders that are neuropathies MUST cause sensory deficits. Inference 1 is logically sound. Inference 2: Statement 2 says \'SOME sensory deficits lead to impaired gait\'. It is not guaranteed that the specific sensory deficits caused by neuropathies belong to this subset, nor that ALL neuropathies lead to impaired gait. Thus, we cannot definitively conclude that no neuropathy is easily treatable.',
    difficulty: 'Medium',
    type: 'Standard',
    cognitiveLevel: 'Analysis',
    source: 'AI_GENERATED',
    sourceReference: 'NMDCAT preparation',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
    status: 'AI_GENERATED',
    verificationStatus: 'AI_GENERATED',
    authorType: 'AI',
    generationModel: 'gemini-flash-latest'
  }
];

// Simple validation
console.log(`Total questions to seed: ${seedQuestions.length}`);

// Function to check for existing questions by question text
async function checkForExistingQuestions(): Promise<Set<string>> {
  try {
    const collectionRef = collection(db, 'mcqs');
    const snapshot = await getDocs(collectionRef);
    const existingQuestions = new Set<string>();
    snapshot.forEach((doc) => {
      const data = doc.data();
      if (data.question) {
        existingQuestions.add(data.question.toLowerCase().trim());
      }
    });
    return existingQuestions;
  } catch (err) {
    console.error('Error checking existing questions:', err);
    return new Set();
  }
}

// Function to execute seeding
async function executeSeeding() {
  console.log('=== STARTING DATABASE SEEDING ===');
  
  // Check for existing questions
  console.log('Checking for existing questions...');
  const existingQuestions = await checkForExistingQuestions();
  console.log(`Found ${existingQuestions.size} existing questions in database`);
  
  // Filter out duplicates
  const newQuestions = seedQuestions.filter(q => {
    const isDuplicate = existingQuestions.has(q.question.toLowerCase().trim());
    if (isDuplicate) {
      console.log(`Skipping duplicate: ${q.question.substring(0, 50)}...`);
    }
    return !isDuplicate;
  });
  
  console.log(`Questions to insert: ${newQuestions.length}`);
  console.log(`Questions skipped as duplicates: ${seedQuestions.length - newQuestions.length}`);
  
  if (newQuestions.length === 0) {
    console.log('No new questions to insert. Seeding complete.');
    return;
  }
  
  // Stage the questions
  console.log('Staging questions to Firestore...');
  const result = await stageAiGeneratedQuestions(newQuestions, 'system_seed');
  
  if (result.success) {
    console.log(`Successfully staged ${result.staged} questions`);
    
    // For presentation purposes, we need these questions to be PUBLISHED
    // so they're available in Practice mode
    console.log('Publishing questions for presentation availability...');
    
    // Get the staged questions
    const collectionRef = collection(db, 'mcqs');
    const q = query(collectionRef, where('status', '==', 'AI_GENERATED'));
    const snapshot = await getDocs(q);
    
    let publishedCount = 0;
    for (const doc of snapshot.docs) {
      await approveStagedQuestion(doc.id, 'system_seed');
      publishedCount++;
    }
    
    console.log(`Successfully published ${publishedCount} questions`);
  } else {
    console.error('Failed to stage questions');
  }
  
  console.log('=== SEEDING COMPLETE ===');
}

// Execute seeding
executeSeeding().catch(console.error);

export { seedQuestions, executeSeeding };
